In [1]:
#Import packages
import numpy as np
import pandas as pd

In [2]:
#Importing the raw .csv files
billamount = pd.read_csv('data/bill_amount.csv')
billid = pd.read_csv('data/bill_id.csv')
clinicaldata = pd.read_csv('data/clinical_data.csv')
demodata = pd.read_csv('data/demographics.csv')

In [3]:
#Dsiplay basic information of the data
billamount.info()
print('\n')
billid.info()
print('\n')
clinicaldata.info()
print('\n')
demodata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13600 entries, 0 to 13599
Data columns (total 2 columns):
bill_id    13600 non-null int64
amount     13600 non-null float64
dtypes: float64(1), int64(1)
memory usage: 212.6 KB


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13600 entries, 0 to 13599
Data columns (total 3 columns):
bill_id              13600 non-null int64
patient_id           13600 non-null object
date_of_admission    13600 non-null object
dtypes: int64(1), object(2)
memory usage: 318.8+ KB


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3400 entries, 0 to 3399
Data columns (total 26 columns):
id                    3400 non-null object
date_of_admission     3400 non-null object
date_of_discharge     3400 non-null object
medical_history_1     3400 non-null int64
medical_history_2     3167 non-null float64
medical_history_3     3400 non-null object
medical_history_4     3400 non-null int64
medical_history_5     3096 non-null float64
medical_history_6     3400 non-null int64
medical_history_7     3400 non-null int64
preop_medication_1    3400 non-null int64
preop_medication_2    3400 non-null int64
preop_medication_3    3400 non-null int64
preop_medication_4    3400 non-null int64
preop_medication_5    3400 non-null int64
preop_medication_6    3400 non-null int64
symptom_1             3400 non-null int64
symptom_2             3400 non-null int64
symptom_3             3400 non-null int64
symptom_4             3400 non-null int64
symptom_5             3400 non-null int64
lab_result_1          3400 non-null float64
lab_result_2          3400 non-null float64
lab_result_3          3400 non-null float64
weight                3400 non-null float64
height                3400 non-null float64
dtypes: float64(7), int64(15), object(4)
memory usage: 690.7+ KB


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 5 columns):
patient_id         3000 non-null object
gender             3000 non-null object
race               3000 non-null object
resident_status    3000 non-null object
date_of_birth      3000 non-null object
dtypes: object(5)
memory usage: 117.3+ KB

In [4]:
#Check the no. of rows and columns in each data file
print('Shape of the Imported Datasets:')
print('Bill_Amount_Data', billamount.shape)
print('Bill_Id_Data', billid.shape)
print('Clinical_Data', clinicaldata.shape)
print('Demographics_Data', demodata.shape)

Shape of the Imported Datasets:
Bill_Amount_Data (13600, 2)
Bill_Id_Data (13600, 3)
Clinical_Data (3400, 26)
Demographics_Data (3000, 5)

In [5]:
#Merge 'Bill_Amount_Data' and 'Bill_Id_Data' using 'bil_id' column
data1 = pd.merge(billamount, billid, on = 'bill_id')
data1

,bill_id,amount,patient_id,date_of_admission
0,40315104,1552.634830,96a76ec5bbcb1d1562c40b9b972e356d,2012-10-22
1,2660045161,1032.011951,796de06efdad342d3f3a379dff0bd63c,2014-09-28
2,1148334643,6469.605351,1ce104904e9160cf3cfdb3c45b9ce4ff,2014-01-16
3,3818426276,755.965425,afdfe7216d84e13708a19cbca288379a,2013-01-22
4,9833541918,897.347816,b9a0c119dc07e07f88281964f3a4869f,2011-04-22
5,620763456,1027.316873,3201c9dfb9dba0495ee8c27cc030a8c2,2015-10-01
6,8769910680,1039.084883,4b6f5a98810b92bbe8f93e8c7235a88f,2011-08-25
7,1726639695,654.969748,9c5f447669b3644d7080c2bd1c2bd2b3,2013-09-09
8,5493467321,646.704056,a7bc99cb21e748e2bf5b9880ac55a0dd,2015-01-04
9,4661888038,1304.195654,91aeb748ae3d0f6fc82e81073520bc34,2012-04-01
10,541279446,20850.701573,e2eb4c92459103b1b79a67cc5c42444c,2012-11-19
11,4302582246,684.409265,9c5f447669b3644d7080c2bd1c2bd2b3,2013-09-09
12,4305678046,4973.101544,2d8084856146882e4e8d703581c30b4f,2011-12-17
13,387576479,1364.026848,cb3fa4745f6f300bd88046b441e12f5b,2011-10-14
14,1625888592,1493.109694,a129e051229c73c0428edf92bb0b3a41,2015-05-14
15,9037494597,393.929020,ab1318e8893ee9805872445be90cc74e,2015-05-02
16,3410185175,1245.566566,09f2aa11e63c70950cce715571c07730,2013-09-04
17,3142388767,7061.573447,7e7d4d3ee5f05a38a6267888a8186ad2,2015-01-14
18,4947360239,27939.528491,823e89a2419de712c0e8fc3a42b9d0c4,2012-01-23
19,8988986555,376.909682,87a483a68c73ae234498bc060f486908,2014-12-13
20,5793869448,21602.080226,a08ec4ff64c7c4ad2f87560e68acd5d5,2011-05-06
21,5578326485,955.781520,2e14e5fa058673fbdb4e525403be304a,2012-04-02
22,7559345184,2005.040995,e6b3aede1195f2cd8bc0ca27baf86255,2015-05-28
23,687515815,1293.456733,31bf634e57e001b75034b598f3806d2c,2015-11-09
24,9060304263,34276.995801,b35f08230dbc37cb02e4c19c89261247,2014-01-09
25,8273353497,976.869083,53bce74ea43151196a040ff1de0500bf,2012-04-17
26,4842810965,26025.521128,dd8f81a50380e0f9238cda2728a5d842,2013-02-21
27,9685543469,5325.944282,91db2ff2302e1bea6ac7afc6bab1a8c4,2015-10-20
28,8338616884,1455.331731,143f0e6182aea0b539ffc8a953d5ebdc,2015-04-20
29,9423605440,835.548234,c18f4c4f3e9794cc1029dba46dda3461,2012-02-08
...,...,...,...,...
13570,821677478,967.302496,1c5442f7a63e7311c19c42fb64cb3595,2011-04-09
13571,8187418887,2437.824003,d85ad62ecab3246924949c64e53e7599,2015-01-15
13572,1342197149,1065.211251,7c3453c5a095c7c2008c9f11cba6ca64,2015-08-18
13573,1981435096,1177.274385,b59347b6652cc3e9ab8cf8b9dbee326d,2011-09-21
13574,2560833099,862.937336,de3dfed0605c58f079824211d8f478bc,2013-08-08
13575,9572933615,1558.885043,e0d48715348591080b104be70fc482db,2013-02-10
13576,5195816957,675.223002,fab697423ff22c140833dfd57cf7ecde,2014-06-27
13577,3456141339,4099.078654,a4aba2d0692294c7dde8031b94ceeac9,2015-02-22
13578,1531092284,11275.677689,fe3f9153937d9275b4f4b468c65bd098,2015-04-21
13579,2590275200,25027.226762,813a1f1142ccd7d2db4db7ee806a9b63,2013-06-16
13580,6579203531,3389.723301,cd0c51b3087df84b452ce04d22782221,2011-07-21
13581,2839933695,12590.264805,0d05a34c7fc070f5fec17a5f545a5148,2011-04-15
13582,8030535192,2288.653295,8a1c7af91e1321a224dafe9a085b1bd8,2011-12-14
13583,6202524478,723.536598,a1bb69b4ec9b42d812bc4161805203b9,2014-07-21
13584,9742021703,17044.331954,e55f2e7001208cd6e1b12d19857ee902,2015-07-03
13585,3815530913,739.968886,f27c4e7587c5ed6765fccf390484cdd4,2014-01-07
13586,4752639471,1068.585996,933dd7c264978c72af9304714dbfee31,2012-12-01
13587,620039216,2297.274530,1b9dc8d9afa26ac24c26bf647e53bd45,2015-05-01
13588,1205762797,10794.635925,050df896aaa8cbad8fc1988bc1f79ebc,2015-10-13
13589,7118473654,855.610879,2fa46d6ff7f4b724089714b6e17a7007,2014-12-26
13590,5815423299,2715.824876,6d91c86852e636adc75d6c7f64f4b12f,2013-09-19
13591,3055449411,3861.467219,41c9f6e5c9bfc0a39afea9eb3dfa4984,2013-10-01
13592,8296027975,1090.583338,07ae0be74d34cf66e0d430e5f597b92e,2013-07-07
13593,8505463896,1222.078787,2f8b615ec9fb2913bd501d3312c4c233,2012-06-13
13594,4818359896,13473.708810,301ed08603424b1b74c8971119d26625,2012-05-27
13595,9046631672,1281.877819,e6b86ad95044e2e5544a10d32dc3e4d4,2013-12-02
13596,932340787,873.625512,848309c0d0848eea411ccd9e12cb0513,2015-10-05
13597,343247663,698.281172,30ad466717b7a6e9e6a22578572438b5,2014-01-25
13598,2953100420,1220.967486,874491426098c8bc16b4620d8aaabc2d,2011-07-25
13599,2885532130,885.105867,fb2d798dce78ee2ab54d454ed3dfb1cc,2015-07-27

In [6]:
#Merge 'Clinical_Data' and 'Demographics_Data' using 'patient_id' column
data2 = pd.merge(clinicaldata, demodata, left_on = 'id', right_on = 'patient_id')
data2

,id,date_of_admission,date_of_discharge,medical_history_1,medical_history_2,medical_history_3,medical_history_4,medical_history_5,medical_history_6,medical_history_7,...,lab_result_1,lab_result_2,lab_result_3,weight,height,patient_id,gender,race,resident_status,date_of_birth
0,1d21f2be18683991eb93d182d6b2d220,2011-01-01,2011-01-11,0,1.0,0,0,0.0,0,0,...,13.2,30.9,123.0,71.3,161.0,1d21f2be18683991eb93d182d6b2d220,Male,Indian,Singaporean,1976-12-19
1,1d21f2be18683991eb93d182d6b2d220,2015-09-17,2015-09-30,0,0.0,0,0,0.0,0,1,...,16.4,23.7,108.0,72.3,161.0,1d21f2be18683991eb93d182d6b2d220,Male,Indian,Singaporean,1976-12-19
2,62bdca0b95d97e99e1c712048fb9fd09,2011-01-01,2011-01-11,0,0.0,0,0,0.0,0,0,...,13.8,22.6,89.0,78.4,160.0,62bdca0b95d97e99e1c712048fb9fd09,Female,Malay,Singaporean,1978-07-20
3,c85cf97bc6307ded0dd4fef8bad2fa09,2011-01-02,2011-01-13,0,0.0,0,0,0.0,0,0,...,11.2,26.2,100.0,72.0,151.0,c85cf97bc6307ded0dd4fef8bad2fa09,Female,Indian,Singaporean,1967-08-14
4,c85cf97bc6307ded0dd4fef8bad2fa09,2014-03-20,2014-03-26,1,0.0,1,0,0.0,1,0,...,18.6,28.4,88.0,72.0,151.0,c85cf97bc6307ded0dd4fef8bad2fa09,Female,Indian,Singaporean,1967-08-14
5,e0397dd72caf4552c5babebd3d61736c,2011-01-02,2011-01-14,0,1.0,No,0,0.0,1,1,...,13.3,28.4,76.0,64.4,152.0,e0397dd72caf4552c5babebd3d61736c,Female,Chinese,PR,1967-12-06
6,94ade3cd5f66f4584902554dff170a29,2011-01-08,2011-01-16,0,0.0,No,0,0.0,1,1,...,12.0,27.8,87.0,55.6,160.0,94ade3cd5f66f4584902554dff170a29,Female,Others,PR,1982-07-18
7,59e07adc2dbc5f70131f57d003610d74,2011-01-07,2011-01-17,0,NaN,No,0,NaN,0,0,...,15.8,31.0,75.0,78.8,169.0,59e07adc2dbc5f70131f57d003610d74,Male,Chinese,Singaporean,1974-01-14
8,f5c4d97ebf32d49967fbf4f6c5fd52ec,2011-01-06,2011-01-17,0,0.0,0,0,0.0,0,1,...,12.1,23.0,83.0,81.8,164.0,f5c4d97ebf32d49967fbf4f6c5fd52ec,Female,Malay,Singapore citizen,1934-04-24
9,1e788744568c21b390c5aa8c5dd61335,2011-01-07,2011-01-17,0,0.0,0,0,0.0,0,1,...,16.4,26.8,126.0,73.5,173.0,1e788744568c21b390c5aa8c5dd61335,Male,Chinese,Singaporean,1961-12-23
10,457402b26562d41f4e40906d3d17d5d1,2011-01-12,2011-01-18,0,0.0,No,0,0.0,0,0,...,12.5,32.9,87.0,98.4,166.0,457402b26562d41f4e40906d3d17d5d1,m,Chinese,Singaporean,1967-06-04
11,79f52395dab0e6d3a03c48f765cb6562,2011-01-02,2011-01-18,0,0.0,0,0,0.0,0,1,...,12.1,23.6,109.0,92.8,176.0,79f52395dab0e6d3a03c48f765cb6562,Male,Chinese,Singapore citizen,1936-04-05
12,d45fcf3bec63ae3b436be42fad33b9e0,2011-01-12,2011-01-18,1,NaN,No,1,0.0,0,0,...,17.0,27.7,116.0,91.6,169.0,d45fcf3bec63ae3b436be42fad33b9e0,Male,chinese,PR,1934-09-02
13,e83f56a339b8a09e87128aa34a7c5a37,2011-01-09,2011-01-20,0,1.0,0,0,0.0,1,0,...,16.0,26.9,102.0,83.4,178.0,e83f56a339b8a09e87128aa34a7c5a37,Male,Chinese,Foreigner,1932-09-19
14,35ec0e9e49240db8e864abb3b9b536fa,2011-01-11,2011-01-22,1,0.0,0,0,0.0,0,1,...,13.1,25.0,108.0,74.9,160.0,35ec0e9e49240db8e864abb3b9b536fa,Female,Malay,Singaporean,1981-06-19
15,7f8e1a194c89076622a7f99cd835e170,2011-01-14,2011-01-22,0,1.0,1,0,0.0,1,0,...,16.4,27.5,106.0,68.2,167.0,7f8e1a194c89076622a7f99cd835e170,Male,Indian,Singapore citizen,1947-10-12
16,c59af905597b9be72420bbdbdad2ce42,2011-01-10,2011-01-22,0,NaN,0,0,NaN,0,0,...,15.6,30.9,87.0,71.1,177.0,c59af905597b9be72420bbdbdad2ce42,Male,Chinese,Singaporean,1958-10-02
17,5506a60f60c2bead138b202125fd96a1,2011-01-07,2011-01-22,0,0.0,0,1,0.0,0,0,...,13.7,25.6,88.0,73.3,154.0,5506a60f60c2bead138b202125fd96a1,Female,India,Singaporean,1948-11-21
18,e515a9f3fc49e257d4134353e139fc14,2011-01-12,2011-01-23,1,0.0,1,0,0.0,0,0,...,14.2,26.1,112.0,94.7,158.0,e515a9f3fc49e257d4134353e139fc14,Female,Chinese,Singapore citizen,1947-11-18
19,47ae732a4ba3b04636007b191f09c71c,2011-01-17,2011-01-24,0,1.0,0,0,0.0,0,0,...,16.6,26.4,84.0,85.0,168.0,47ae732a4ba3b04636007b191f09c71c,Male,Chinese,Foreigner,1971-10-15
20,23d863fd6687215f59672c637302ac77,2011-01-15,2011-01-24,0,0.0,0,0,0.0,1,0,...,13.0,24.1,98.0,76.5,157.0,23d863fd6687215f59672c637302ac77,Female,Chinese,Singaporean,1980-04-16
21,23d863fd6687215f59672c637302ac77,2013-06-22,2013-07-11,0,1.0,Yes,0,1.0,1,0,...,13.2,27.2,128.0,76.5,157.0,23d863fd6687215f59672c637302ac77,Female,Chinese,Singaporean,1980-04-16
22,7ed882e1ea4749ba31bcbe04efd15798,2011-01-11,2011-01-24,1,0.0,0,0,0.0,1,0,...,12.8,29.5,95.0,81.0,160.0,7ed882e1ea4749ba31bcbe04efd15798,Female,Malay,Singaporean,1952-07-19
23,7ce28b0d1309e0a2a74e38747ebd3f6c,2011-01-11,2011-01-25,0,NaN,No,0,0.0,1,0,...,14.0,31.3,123.0,88.0,151.0,7ce28b0d1309e0a2a74e38747ebd3f6c,Female,Malay,Singapore citizen,1983-02-06
24,36c9414a9f8e2c96b286e4afd2acddaa,2011-01-18,2011-01-25,0,0.0,No,0,0.0,0,0,...,13.3,30.1,91.0,62.9,162.0,36c9414a9f8e2c96b286e4afd2acddaa,Female,Chinese,Singapore citizen,1972-10-14
25,c9809bb40710a9079848f06d47ef980b,2011-01-14,2011-01-25,0,NaN,1,0,0.0,0,0,...,15.2,25.2,70.0,79.1,167.0,c9809bb40710a9079848f06d47ef980b,Male,Indian,Singaporean,1982-11-03
26,ff6de9534e28ea31f928ac79c399ecd6,2011-01-13,2011-01-26,0,1.0,Yes,0,0.0,0,0,...,16.2,28.5,89.0,70.0,157.0,ff6de9534e28ea31f928ac79c399ecd6,Female,Chinese,Singaporean,1974-02-20
27,ff6de9534e28ea31f928ac79c399ecd6,2012-10-07,2012-10-13,0,0.0,0,0,0.0,1,0,...,14.1,25.5,88.0,66.0,157.0,ff6de9534e28ea31f928ac79c399ecd6,Female,Chinese,Singaporean,1974-02-20
28,66fada734c11adcf5697a452ab1bb7c5,2011-01-15,2011-01-27,0,1.0,0,0,0.0,1,0,...,15.3,30.3,107.0,95.0,183.0,66fada734c11adcf5697a452ab1bb7c5,Male,Chinese,PR,1951-03-19
29,7e0201eb1cd3f78f99e78df3871a2423,2011-01-18,2011-01-27,0,0.0,Yes,0,0.0,1,0,...,12.8,27.3,108.0,49.4,153.0,7e0201eb1cd3f78f99e78df3871a2423,f,Malay,Singapore citizen,1956-08-05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3370,12e843bd4ae8bdb2bcf4787981f83ddb,2015-12-03,2015-12-17,1,0.0,0,0,1.0,0,0,...,13.4,32.1,126.0,89.1,164.0,12e843bd4ae8bdb2bcf4787981f83ddb,Male,Others,Singapore citizen,1961-11-01
3371,b61adc185e63ce1083922c529d6fff86,2015-12-11,2015-12-18,0,1.0,0,0,0.0,0,1,...,16.0,27.1,92.0,97.3,169.0,b61adc185e63ce1083922c529d6fff86,Male,Malay,Singapore citizen,1971-01-06
3372,1251820cab5f4a4aa4987d49291990e4,2015-12-12,2015-12-18,0,0.0,0,0,0.0,1,1,...,14.9,24.5,88.0,79.4,177.0,1251820cab5f4a4aa4987d49291990e4,Male,Malay,PR,1941-01-03
3373,c5bc1e7b20adad5380cb7588d6101944,2015-12-10,2015-12-19,0,1.0,0,0,0.0,0,1,...,16.4,26.6,92.0,77.3,174.0,c5bc1e7b20adad5380cb7588d6101944,Male,Malay,Singaporean,1958-09-20
3374,ec22f79fd1ead23a6589b599ea74a40f,2015-12-07,2015-12-20,0,0.0,0,0,0.0,0,0,...,12.4,29.6,103.0,78.0,161.0,ec22f79fd1ead23a6589b599ea74a40f,Female,Malay,Singaporean,1945-10-20
3375,8bfea26b4f6899a73dcc0bfe00bfd9a5,2015-12-04,2015-12-20,0,0.0,0,0,NaN,0,0,...,11.0,27.4,109.0,80.1,164.0,8bfea26b4f6899a73dcc0bfe00bfd9a5,m,Chinese,PR,1963-10-17
3376,faff8a7640b94e712431922ee41ea9b3,2015-12-14,2015-12-20,0,0.0,0,0,0.0,0,0,...,18.2,26.5,84.0,81.8,158.0,faff8a7640b94e712431922ee41ea9b3,Female,Chinese,Singaporean,1961-06-15
3377,53f75e54d6bbc965d9b58ddfb8314dee,2015-12-07,2015-12-21,0,0.0,0,0,0.0,0,1,...,16.2,24.2,86.0,79.9,160.0,53f75e54d6bbc965d9b58ddfb8314dee,Female,chinese,Singapore citizen,1978-08-22
3378,32fda904a93b82d452c82a8a231b938b,2015-12-06,2015-12-21,0,0.0,0,0,0.0,1,1,...,15.8,25.2,132.0,81.0,163.0,32fda904a93b82d452c82a8a231b938b,Female,Malay,Singapore citizen,1943-11-22
3379,c8e000412c4e82b29e6948bd79c0be86,2015-12-18,2015-12-23,0,0.0,No,0,0.0,0,0,...,17.3,30.1,84.0,89.0,166.0,c8e000412c4e82b29e6948bd79c0be86,Male,Chinese,PR,1963-06-13
3380,d59a325e8cb08e77a14eefe7afc02c58,2015-12-10,2015-12-24,0,0.0,1,0,0.0,0,0,...,14.9,26.3,131.0,75.4,168.0,d59a325e8cb08e77a14eefe7afc02c58,Male,chinese,Singaporean,1953-06-27
3381,493c1170ab4438b7aa300bb10b99bf7a,2015-12-19,2015-12-25,0,1.0,0,0,0.0,1,0,...,14.2,30.7,116.0,90.4,170.0,493c1170ab4438b7aa300bb10b99bf7a,Male,Malay,Singaporean,1976-02-02
3382,2e42488ef946664f8e5b3ce6d5a7c631,2015-12-13,2015-12-26,0,1.0,0,0,0.0,0,0,...,16.2,25.8,113.0,61.0,159.0,2e42488ef946664f8e5b3ce6d5a7c631,Female,Chinese,Foreigner,1953-07-22
3383,24bed696100d7b1bc27dffa59017d80c,2015-12-10,2015-12-26,0,1.0,1,0,0.0,0,0,...,15.2,29.0,121.0,72.0,158.0,24bed696100d7b1bc27dffa59017d80c,Female,Malay,Singapore citizen,1956-07-07
3384,d7fd45590b031def3fdaabf7ac8d71c9,2015-12-20,2015-12-27,1,1.0,0,1,0.0,0,0,...,13.9,27.4,106.0,79.7,159.0,d7fd45590b031def3fdaabf7ac8d71c9,Female,Chinese,Singaporean,1942-09-27
3385,c676a4d6ae2bc1eb9b998d7d8bc3876c,2015-12-15,2015-12-27,0,0.0,0,0,1.0,0,0,...,15.0,22.7,87.0,76.6,166.0,c676a4d6ae2bc1eb9b998d7d8bc3876c,m,Chinese,Singaporean,1966-08-09
3386,c4e4a24e744e18a93d616a3e8aabb7c8,2015-12-20,2015-12-28,0,1.0,0,0,0.0,0,0,...,13.0,30.9,84.0,76.8,171.0,c4e4a24e744e18a93d616a3e8aabb7c8,Female,Malay,Foreigner,1969-01-21
3387,be9f6767432045cd1a0d71b6afbd015a,2015-12-16,2015-12-28,0,0.0,1,0,NaN,0,0,...,14.7,27.1,94.0,70.4,151.0,be9f6767432045cd1a0d71b6afbd015a,Female,Chinese,Singaporean,1969-07-28
3388,228e27d883c5bd9af820add27c253d53,2015-12-24,2015-12-30,0,NaN,No,0,0.0,1,0,...,12.4,25.8,87.0,80.3,162.0,228e27d883c5bd9af820add27c253d53,Male,Chinese,PR,1976-09-13
3389,88c4398a07dca73daf538c5eb4ee5167,2015-12-20,2015-12-31,0,1.0,1,0,0.0,0,0,...,15.6,28.5,85.0,57.0,170.0,88c4398a07dca73daf538c5eb4ee5167,Male,Chinese,Singaporean,1948-12-19
3390,336bfb12d416ddf4a2475bb00b318cf1,2015-12-19,2016-01-01,0,NaN,0,0,0.0,0,1,...,12.9,28.1,98.0,92.9,151.0,336bfb12d416ddf4a2475bb00b318cf1,Female,Chinese,PR,1946-12-10
3391,38f1913aa919889718a6c4c4b114490f,2015-12-20,2016-01-02,0,0.0,1,0,0.0,1,1,...,17.0,27.0,84.0,71.2,160.0,38f1913aa919889718a6c4c4b114490f,Female,Chinese,Singaporean,1977-10-10
3392,80c4d7e0a93e353e201cb83c776b0bad,2015-12-25,2016-01-03,0,0.0,0,0,0.0,0,0,...,15.8,26.6,72.0,72.2,157.0,80c4d7e0a93e353e201cb83c776b0bad,Female,chinese,Singaporean,1969-03-27
3393,1001a2f4a4e11a5761e79f30c0b8d875,2015-12-26,2016-01-04,1,0.0,1,0,0.0,0,1,...,15.3,23.4,120.0,72.5,164.0,1001a2f4a4e11a5761e79f30c0b8d875,Female,Chinese,Singapore citizen,1971-08-27
3394,f253e6e69fdc53f07ec682df8ed1a80e,2015-12-21,2016-01-05,0,0.0,0,0,0.0,0,0,...,16.3,27.6,114.0,91.7,166.0,f253e6e69fdc53f07ec682df8ed1a80e,Male,Chinese,Foreigner,1964-10-12
3395,3f052a68d7c25d817a63aa1ba70f4dc2,2015-12-21,2016-01-06,0,0.0,0,0,0.0,0,0,...,12.9,27.9,106.0,84.8,162.0,3f052a68d7c25d817a63aa1ba70f4dc2,Female,Chinese,Singaporean,1943-06-22
3396,4f67a54ab205cc9e7e2b0a4ee08e4fba,2015-12-28,2016-01-07,0,0.0,0,0,0.0,1,0,...,11.6,27.9,107.0,72.7,155.0,4f67a54ab205cc9e7e2b0a4ee08e4fba,Female,Chinese,Singaporean,1970-08-07
3397,ac52a32f8ce8c46d82df2d72052ae5a9,2015-12-28,2016-01-08,0,0.0,0,0,0.0,1,0,...,14.7,25.2,91.0,62.3,154.0,ac52a32f8ce8c46d82df2d72052ae5a9,Female,Chinese,Singapore citizen,1979-03-06
3398,5189c62dfb8e6075b5c7fd4766671bd4,2015-12-26,2016-01-09,0,1.0,0,0,NaN,0,0,...,16.9,25.6,92.0,87.3,156.0,5189c62dfb8e6075b5c7fd4766671bd4,Female,chinese,Singaporean,1960-05-10
3399,a4c61deaa9ce86b4d2289eab6128b872,2015-12-28,2016-01-11,0,NaN,1,0,0.0,0,0,...,17.8,25.8,78.0,82.9,164.0,a4c61deaa9ce86b4d2289eab6128b872,Male,Chinese,Singaporean,1976-10-19

In [7]:
#Merge 'data1' and 'data2' using patient_id and date of admissions columns.
data3 = pd.merge(data1, data2, left_on = ['patient_id', 'date_of_admission'], right_on = ['id', 'date_of_admission'])
#Drop redundant column
data3 = data3.drop('id', axis=1).rename(columns = {'patient_id_x' : 'patient_id'})
data3

,bill_id,amount,patient_id,date_of_admission,date_of_discharge,medical_history_1,medical_history_2,medical_history_3,medical_history_4,medical_history_5,...,lab_result_1,lab_result_2,lab_result_3,weight,height,patient_id_y,gender,race,resident_status,date_of_birth
0,40315104,1552.634830,96a76ec5bbcb1d1562c40b9b972e356d,2012-10-22,2012-11-03,0,0.0,0,0,0.0,...,17.6,31.8,98.0,65.1,166.0,96a76ec5bbcb1d1562c40b9b972e356d,Female,Malay,Singaporean,1967-05-15
1,7040712549,27923.446312,96a76ec5bbcb1d1562c40b9b972e356d,2012-10-22,2012-11-03,0,0.0,0,0,0.0,...,17.6,31.8,98.0,65.1,166.0,96a76ec5bbcb1d1562c40b9b972e356d,Female,Malay,Singaporean,1967-05-15
2,1314727123,1952.978141,96a76ec5bbcb1d1562c40b9b972e356d,2012-10-22,2012-11-03,0,0.0,0,0,0.0,...,17.6,31.8,98.0,65.1,166.0,96a76ec5bbcb1d1562c40b9b972e356d,Female,Malay,Singaporean,1967-05-15
3,1029762870,1244.994422,96a76ec5bbcb1d1562c40b9b972e356d,2012-10-22,2012-11-03,0,0.0,0,0,0.0,...,17.6,31.8,98.0,65.1,166.0,96a76ec5bbcb1d1562c40b9b972e356d,Female,Malay,Singaporean,1967-05-15
4,2660045161,1032.011951,796de06efdad342d3f3a379dff0bd63c,2014-09-28,2014-10-11,0,0.0,0,0,0.0,...,16.3,29.1,94.0,72.5,162.0,796de06efdad342d3f3a379dff0bd63c,Female,chinese,Singapore citizen,1973-05-28
5,5243221793,8247.773511,796de06efdad342d3f3a379dff0bd63c,2014-09-28,2014-10-11,0,0.0,0,0,0.0,...,16.3,29.1,94.0,72.5,162.0,796de06efdad342d3f3a379dff0bd63c,Female,chinese,Singapore citizen,1973-05-28
6,7295330948,624.157007,796de06efdad342d3f3a379dff0bd63c,2014-09-28,2014-10-11,0,0.0,0,0,0.0,...,16.3,29.1,94.0,72.5,162.0,796de06efdad342d3f3a379dff0bd63c,Female,chinese,Singapore citizen,1973-05-28
7,5852145580,621.841294,796de06efdad342d3f3a379dff0bd63c,2014-09-28,2014-10-11,0,0.0,0,0,0.0,...,16.3,29.1,94.0,72.5,162.0,796de06efdad342d3f3a379dff0bd63c,Female,chinese,Singapore citizen,1973-05-28
8,1148334643,6469.605351,1ce104904e9160cf3cfdb3c45b9ce4ff,2014-01-16,2014-01-26,1,1.0,1,0,1.0,...,10.6,27.3,89.0,69.0,162.0,1ce104904e9160cf3cfdb3c45b9ce4ff,Female,Chinese,PR,1980-06-21
9,7272265263,14334.244765,1ce104904e9160cf3cfdb3c45b9ce4ff,2014-01-16,2014-01-26,1,1.0,1,0,1.0,...,10.6,27.3,89.0,69.0,162.0,1ce104904e9160cf3cfdb3c45b9ce4ff,Female,Chinese,PR,1980-06-21
10,3584162596,844.558698,1ce104904e9160cf3cfdb3c45b9ce4ff,2014-01-16,2014-01-26,1,1.0,1,0,1.0,...,10.6,27.3,89.0,69.0,162.0,1ce104904e9160cf3cfdb3c45b9ce4ff,Female,Chinese,PR,1980-06-21
11,7306770288,721.834000,1ce104904e9160cf3cfdb3c45b9ce4ff,2014-01-16,2014-01-26,1,1.0,1,0,1.0,...,10.6,27.3,89.0,69.0,162.0,1ce104904e9160cf3cfdb3c45b9ce4ff,Female,Chinese,PR,1980-06-21
12,3818426276,755.965425,afdfe7216d84e13708a19cbca288379a,2013-01-22,2013-01-31,0,1.0,No,0,0.0,...,13.9,29.6,102.0,105.2,166.0,afdfe7216d84e13708a19cbca288379a,Male,Chinese,Singapore citizen,1951-02-19
13,1237824219,1257.756384,afdfe7216d84e13708a19cbca288379a,2013-01-22,2013-01-31,0,1.0,No,0,0.0,...,13.9,29.6,102.0,105.2,166.0,afdfe7216d84e13708a19cbca288379a,Male,Chinese,Singapore citizen,1951-02-19
14,1807983760,20285.301427,afdfe7216d84e13708a19cbca288379a,2013-01-22,2013-01-31,0,1.0,No,0,0.0,...,13.9,29.6,102.0,105.2,166.0,afdfe7216d84e13708a19cbca288379a,Male,Chinese,Singapore citizen,1951-02-19
15,4741780051,431.980243,afdfe7216d84e13708a19cbca288379a,2013-01-22,2013-01-31,0,1.0,No,0,0.0,...,13.9,29.6,102.0,105.2,166.0,afdfe7216d84e13708a19cbca288379a,Male,Chinese,Singapore citizen,1951-02-19
16,9833541918,897.347816,b9a0c119dc07e07f88281964f3a4869f,2011-04-22,2011-05-04,1,0.0,0,0,0.0,...,11.0,25.0,86.0,66.3,161.0,b9a0c119dc07e07f88281964f3a4869f,Male,Chinese,Singaporean,1972-03-19
17,3177516777,6779.135342,b9a0c119dc07e07f88281964f3a4869f,2011-04-22,2011-05-04,1,0.0,0,0,0.0,...,11.0,25.0,86.0,66.3,161.0,b9a0c119dc07e07f88281964f3a4869f,Male,Chinese,Singaporean,1972-03-19
18,6534375541,14459.537935,b9a0c119dc07e07f88281964f3a4869f,2011-04-22,2011-05-04,1,0.0,0,0,0.0,...,11.0,25.0,86.0,66.3,161.0,b9a0c119dc07e07f88281964f3a4869f,Male,Chinese,Singaporean,1972-03-19
19,4732311687,751.044780,b9a0c119dc07e07f88281964f3a4869f,2011-04-22,2011-05-04,1,0.0,0,0,0.0,...,11.0,25.0,86.0,66.3,161.0,b9a0c119dc07e07f88281964f3a4869f,Male,Chinese,Singaporean,1972-03-19
20,620763456,1027.316873,3201c9dfb9dba0495ee8c27cc030a8c2,2015-10-01,2015-10-11,0,1.0,0,0,0.0,...,16.4,28.4,111.0,73.0,155.0,3201c9dfb9dba0495ee8c27cc030a8c2,Female,Malay,Singapore citizen,1971-06-06
21,6271756123,1782.362826,3201c9dfb9dba0495ee8c27cc030a8c2,2015-10-01,2015-10-11,0,1.0,0,0,0.0,...,16.4,28.4,111.0,73.0,155.0,3201c9dfb9dba0495ee8c27cc030a8c2,Female,Malay,Singapore citizen,1971-06-06
22,7236145252,5461.510894,3201c9dfb9dba0495ee8c27cc030a8c2,2015-10-01,2015-10-11,0,1.0,0,0,0.0,...,16.4,28.4,111.0,73.0,155.0,3201c9dfb9dba0495ee8c27cc030a8c2,Female,Malay,Singapore citizen,1971-06-06
23,5849181734,18250.671176,3201c9dfb9dba0495ee8c27cc030a8c2,2015-10-01,2015-10-11,0,1.0,0,0,0.0,...,16.4,28.4,111.0,73.0,155.0,3201c9dfb9dba0495ee8c27cc030a8c2,Female,Malay,Singapore citizen,1971-06-06
24,8769910680,1039.084883,4b6f5a98810b92bbe8f93e8c7235a88f,2011-08-25,2011-09-10,0,0.0,0,0,0.0,...,14.4,26.2,83.0,65.8,172.0,4b6f5a98810b92bbe8f93e8c7235a88f,Male,Chinese,Singaporean,1970-05-15
25,3818710125,8362.437297,4b6f5a98810b92bbe8f93e8c7235a88f,2011-08-25,2011-09-10,0,0.0,0,0,0.0,...,14.4,26.2,83.0,65.8,172.0,4b6f5a98810b92bbe8f93e8c7235a88f,Male,Chinese,Singaporean,1970-05-15
26,2907144128,2911.501316,4b6f5a98810b92bbe8f93e8c7235a88f,2011-08-25,2011-09-10,0,0.0,0,0,0.0,...,14.4,26.2,83.0,65.8,172.0,4b6f5a98810b92bbe8f93e8c7235a88f,Male,Chinese,Singaporean,1970-05-15
27,3536678511,519.169085,4b6f5a98810b92bbe8f93e8c7235a88f,2011-08-25,2011-09-10,0,0.0,0,0,0.0,...,14.4,26.2,83.0,65.8,172.0,4b6f5a98810b92bbe8f93e8c7235a88f,Male,Chinese,Singaporean,1970-05-15
28,1726639695,654.969748,9c5f447669b3644d7080c2bd1c2bd2b3,2013-09-09,2013-09-23,0,0.0,0,0,0.0,...,16.7,28.2,91.0,53.0,159.0,9c5f447669b3644d7080c2bd1c2bd2b3,Female,Chinese,Singaporean,1946-09-03
29,4302582246,684.409265,9c5f447669b3644d7080c2bd1c2bd2b3,2013-09-09,2013-09-23,0,0.0,0,0,0.0,...,16.7,28.2,91.0,53.0,159.0,9c5f447669b3644d7080c2bd1c2bd2b3,Female,Chinese,Singaporean,1946-09-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13570,1665258244,791.322103,861a1eaa063568038c9b54af4980cde5,2013-09-27,2013-10-07,0,0.0,0,0,0.0,...,15.6,28.5,81.0,73.5,162.0,861a1eaa063568038c9b54af4980cde5,Female,Chinese,Singaporean,1948-02-28
13571,6602866802,831.507503,861a1eaa063568038c9b54af4980cde5,2013-09-27,2013-10-07,0,0.0,0,0,0.0,...,15.6,28.5,81.0,73.5,162.0,861a1eaa063568038c9b54af4980cde5,Female,Chinese,Singaporean,1948-02-28
13572,9343005460,1027.542779,52fdfa7f874fc92a5d1f73fd8a11911b,2012-08-17,2012-08-26,0,0.0,0,0,NaN,...,12.7,28.0,134.0,71.7,163.0,52fdfa7f874fc92a5d1f73fd8a11911b,Female,Indian,Singapore citizen,1974-09-17
13573,9339329912,20982.495300,52fdfa7f874fc92a5d1f73fd8a11911b,2012-08-17,2012-08-26,0,0.0,0,0,NaN,...,12.7,28.0,134.0,71.7,163.0,52fdfa7f874fc92a5d1f73fd8a11911b,Female,Indian,Singapore citizen,1974-09-17
13574,2074795759,719.538562,52fdfa7f874fc92a5d1f73fd8a11911b,2012-08-17,2012-08-26,0,0.0,0,0,NaN,...,12.7,28.0,134.0,71.7,163.0,52fdfa7f874fc92a5d1f73fd8a11911b,Female,Indian,Singapore citizen,1974-09-17
13575,9742898122,927.182792,52fdfa7f874fc92a5d1f73fd8a11911b,2012-08-17,2012-08-26,0,0.0,0,0,NaN,...,12.7,28.0,134.0,71.7,163.0,52fdfa7f874fc92a5d1f73fd8a11911b,Female,Indian,Singapore citizen,1974-09-17
13576,7507162691,1473.572382,67d5260621d5602bed05ec588d9c3ccf,2015-01-07,2015-01-20,0,1.0,1,0,0.0,...,12.5,29.3,63.0,79.2,151.0,67d5260621d5602bed05ec588d9c3ccf,Female,chinese,Singapore citizen,1944-07-21
13577,3899639962,25307.209574,67d5260621d5602bed05ec588d9c3ccf,2015-01-07,2015-01-20,0,1.0,1,0,0.0,...,12.5,29.3,63.0,79.2,151.0,67d5260621d5602bed05ec588d9c3ccf,Female,chinese,Singapore citizen,1944-07-21
13578,6033613326,1830.268463,67d5260621d5602bed05ec588d9c3ccf,2015-01-07,2015-01-20,0,1.0,1,0,0.0,...,12.5,29.3,63.0,79.2,151.0,67d5260621d5602bed05ec588d9c3ccf,Female,chinese,Singapore citizen,1944-07-21
13579,5864590164,2630.797099,67d5260621d5602bed05ec588d9c3ccf,2015-01-07,2015-01-20,0,1.0,1,0,0.0,...,12.5,29.3,63.0,79.2,151.0,67d5260621d5602bed05ec588d9c3ccf,Female,chinese,Singapore citizen,1944-07-21
13580,6902763374,971.445142,21d57214d564717bd9ee1a55b0f40555,2011-10-04,2011-10-13,0,0.0,0,0,0.0,...,15.1,24.1,89.0,89.0,170.0,21d57214d564717bd9ee1a55b0f40555,Male,Others,Singaporean,1973-05-03
13581,2542024990,896.242503,21d57214d564717bd9ee1a55b0f40555,2011-10-04,2011-10-13,0,0.0,0,0,0.0,...,15.1,24.1,89.0,89.0,170.0,21d57214d564717bd9ee1a55b0f40555,Male,Others,Singaporean,1973-05-03
13582,9847108748,731.254525,21d57214d564717bd9ee1a55b0f40555,2011-10-04,2011-10-13,0,0.0,0,0,0.0,...,15.1,24.1,89.0,89.0,170.0,21d57214d564717bd9ee1a55b0f40555,Male,Others,Singaporean,1973-05-03
13583,4104244196,21324.144998,21d57214d564717bd9ee1a55b0f40555,2011-10-04,2011-10-13,0,0.0,0,0,0.0,...,15.1,24.1,89.0,89.0,170.0,21d57214d564717bd9ee1a55b0f40555,Male,Others,Singaporean,1973-05-03
13584,6087670618,24427.027220,836498863454509ae1f0abc0dd128fa9,2013-06-03,2013-06-20,1,0.0,0,0,0.0,...,16.1,25.3,105.0,73.9,167.0,836498863454509ae1f0abc0dd128fa9,Female,Malay,Singaporean,1971-01-26
13585,2767999647,1026.521238,836498863454509ae1f0abc0dd128fa9,2013-06-03,2013-06-20,1,0.0,0,0,0.0,...,16.1,25.3,105.0,73.9,167.0,836498863454509ae1f0abc0dd128fa9,Female,Malay,Singaporean,1971-01-26
13586,1474776806,1625.743877,836498863454509ae1f0abc0dd128fa9,2013-06-03,2013-06-20,1,0.0,0,0,0.0,...,16.1,25.3,105.0,73.9,167.0,836498863454509ae1f0abc0dd128fa9,Female,Malay,Singaporean,1971-01-26
13587,2186673022,11452.241716,836498863454509ae1f0abc0dd128fa9,2013-06-03,2013-06-20,1,0.0,0,0,0.0,...,16.1,25.3,105.0,73.9,167.0,836498863454509ae1f0abc0dd128fa9,Female,Malay,Singaporean,1971-01-26
13588,180722271,994.079078,97e68baf7e61c438a501fc6df124d7b4,2015-07-27,2015-08-09,0,0.0,No,0,0.0,...,14.3,29.7,114.0,66.5,158.0,97e68baf7e61c438a501fc6df124d7b4,Female,Indian,Singaporean,1940-04-27
13589,8823372757,1046.520351,97e68baf7e61c438a501fc6df124d7b4,2015-07-27,2015-08-09,0,0.0,No,0,0.0,...,14.3,29.7,114.0,66.5,158.0,97e68baf7e61c438a501fc6df124d7b4,Female,Indian,Singaporean,1940-04-27
13590,3599833451,28988.383209,97e68baf7e61c438a501fc6df124d7b4,2015-07-27,2015-08-09,0,0.0,No,0,0.0,...,14.3,29.7,114.0,66.5,158.0,97e68baf7e61c438a501fc6df124d7b4,Female,Indian,Singaporean,1940-04-27
13591,9779052072,1736.094278,97e68baf7e61c438a501fc6df124d7b4,2015-07-27,2015-08-09,0,0.0,No,0,0.0,...,14.3,29.7,114.0,66.5,158.0,97e68baf7e61c438a501fc6df124d7b4,Female,Indian,Singaporean,1940-04-27
13592,1620627727,17367.428140,7373cb1310011241d432d36b25c5bca6,2011-09-17,2011-09-27,0,0.0,0,0,0.0,...,15.5,29.5,113.0,75.5,182.0,7373cb1310011241d432d36b25c5bca6,Male,Chinese,Singaporean,1973-09-14
13593,8891673843,2961.620399,7373cb1310011241d432d36b25c5bca6,2011-09-17,2011-09-27,0,0.0,0,0,0.0,...,15.5,29.5,113.0,75.5,182.0,7373cb1310011241d432d36b25c5bca6,Male,Chinese,Singaporean,1973-09-14
13594,6570104328,1249.142294,7373cb1310011241d432d36b25c5bca6,2011-09-17,2011-09-27,0,0.0,0,0,0.0,...,15.5,29.5,113.0,75.5,182.0,7373cb1310011241d432d36b25c5bca6,Male,Chinese,Singaporean,1973-09-14
13595,1123494323,663.585265,7373cb1310011241d432d36b25c5bca6,2011-09-17,2011-09-27,0,0.0,0,0,0.0,...,15.5,29.5,113.0,75.5,182.0,7373cb1310011241d432d36b25c5bca6,Male,Chinese,Singaporean,1973-09-14
13596,8843072066,1324.691516,c607942a9bebf9c61daf2c0da499ddf5,2013-09-16,2013-09-30,0,1.0,0,0,0.0,...,12.1,29.4,115.0,77.8,175.0,c607942a9bebf9c61daf2c0da499ddf5,Male,Malay,Singaporean,1972-01-04
13597,2727258154,18386.672482,c607942a9bebf9c61daf2c0da499ddf5,2013-09-16,2013-09-30,0,1.0,0,0,0.0,...,12.1,29.4,115.0,77.8,175.0,c607942a9bebf9c61daf2c0da499ddf5,Male,Malay,Singaporean,1972-01-04
13598,38401965,5280.005320,c607942a9bebf9c61daf2c0da499ddf5,2013-09-16,2013-09-30,0,1.0,0,0,0.0,...,12.1,29.4,115.0,77.8,175.0,c607942a9bebf9c61daf2c0da499ddf5,Male,Malay,Singaporean,1972-01-04
13599,9020331863,1273.785840,c607942a9bebf9c61daf2c0da499ddf5,2013-09-16,2013-09-30,0,1.0,0,0,0.0,...,12.1,29.4,115.0,77.8,175.0,c607942a9bebf9c61daf2c0da499ddf5,Male,Malay,Singaporean,1972-01-04

In [8]:
#There are records with same patient id, date_of_admission and date_of_discharge but different bill_id
#We sum the bill id of such records by using groupby
grouped_data = data3.groupby(['patient_id', 'date_of_admission',
       'date_of_discharge'])['amount'].apply(lambda x : x.astype(int).sum()).reset_index()

In [9]:
#drop the old amount column from data3 
data3.drop('amount', axis=1, inplace = True)
#drop records that has same patient_id, date_of_admission and date_of_discharge
data3.drop_duplicates(subset=['patient_id', 'date_of_admission','date_of_discharge'], keep='last', inplace=True)
joineddata = pd.merge(left=data3, right=grouped_data, right_index=True, on=['patient_id', 'date_of_admission','date_of_discharge'])
joineddata = joineddata.drop('bill_id', axis=1).reset_index().drop(columns=['index', 'patient_id_y'])
joineddata.to_csv('data/joined_data.csv', index = False)
joineddata

,patient_id,date_of_admission,date_of_discharge,medical_history_1,medical_history_2,medical_history_3,medical_history_4,medical_history_5,medical_history_6,medical_history_7,...,lab_result_1,lab_result_2,lab_result_3,weight,height,gender,race,resident_status,date_of_birth,amount
0,96a76ec5bbcb1d1562c40b9b972e356d,2012-10-22,2012-11-03,0,0.0,0,0,0.0,0,1,...,17.6,31.8,98.0,65.1,166.0,Female,Malay,Singaporean,1967-05-15,32671
1,796de06efdad342d3f3a379dff0bd63c,2014-09-28,2014-10-11,0,0.0,0,0,0.0,0,0,...,16.3,29.1,94.0,72.5,162.0,Female,chinese,Singapore citizen,1973-05-28,10524
2,1ce104904e9160cf3cfdb3c45b9ce4ff,2014-01-16,2014-01-26,1,1.0,1,0,1.0,0,0,...,10.6,27.3,89.0,69.0,162.0,Female,Chinese,PR,1980-06-21,22368
3,afdfe7216d84e13708a19cbca288379a,2013-01-22,2013-01-31,0,1.0,No,0,0.0,0,0,...,13.9,29.6,102.0,105.2,166.0,Male,Chinese,Singapore citizen,1951-02-19,22728
4,b9a0c119dc07e07f88281964f3a4869f,2011-04-22,2011-05-04,1,0.0,0,0,0.0,1,0,...,11.0,25.0,86.0,66.3,161.0,Male,Chinese,Singaporean,1972-03-19,22886
5,3201c9dfb9dba0495ee8c27cc030a8c2,2015-10-01,2015-10-11,0,1.0,0,0,0.0,1,0,...,16.4,28.4,111.0,73.0,155.0,Female,Malay,Singapore citizen,1971-06-06,26520
6,4b6f5a98810b92bbe8f93e8c7235a88f,2011-08-25,2011-09-10,0,0.0,0,0,0.0,1,0,...,14.4,26.2,83.0,65.8,172.0,Male,Chinese,Singaporean,1970-05-15,12831
7,9c5f447669b3644d7080c2bd1c2bd2b3,2013-09-09,2013-09-23,0,0.0,0,0,0.0,0,0,...,16.7,28.2,91.0,53.0,159.0,Female,Chinese,Singaporean,1946-09-03,19201
8,a7bc99cb21e748e2bf5b9880ac55a0dd,2015-01-04,2015-01-20,0,0.0,No,0,0.0,0,0,...,14.0,29.4,104.0,63.6,155.0,Female,Chinese,Singaporean,1941-05-23,13748
9,91aeb748ae3d0f6fc82e81073520bc34,2012-04-01,2012-04-11,0,1.0,0,0,0.0,0,1,...,14.2,29.5,97.0,75.1,172.0,Male,chinese,PR,1950-12-08,27642
10,e2eb4c92459103b1b79a67cc5c42444c,2012-11-19,2012-11-29,1,1.0,0,0,NaN,0,0,...,13.6,29.4,99.0,58.1,159.0,Female,Malay,PR,1978-03-08,29853
11,2d8084856146882e4e8d703581c30b4f,2011-12-17,2011-12-29,0,NaN,0,0,0.0,0,0,...,13.8,28.8,120.0,67.6,158.0,Female,Malay,Singapore citizen,1975-03-07,8677
12,cb3fa4745f6f300bd88046b441e12f5b,2011-10-14,2011-10-23,0,0.0,0,0,0.0,1,0,...,12.5,24.7,63.0,59.2,165.0,Female,Malay,Singaporean,1982-03-11,10950
13,a129e051229c73c0428edf92bb0b3a41,2015-05-14,2015-05-25,0,0.0,0,0,0.0,0,1,...,17.2,31.7,101.0,97.6,175.0,Male,Malay,Singapore citizen,1982-12-13,13311
14,ab1318e8893ee9805872445be90cc74e,2015-05-02,2015-05-14,0,1.0,0,0,0.0,1,1,...,13.9,27.2,105.0,88.3,168.0,Male,chinese,Singapore citizen,1967-02-13,15852
15,09f2aa11e63c70950cce715571c07730,2013-09-04,2013-09-12,0,0.0,Yes,0,0.0,0,0,...,13.6,31.0,113.0,66.1,158.0,Female,Chinese,Singaporean,1945-07-18,14950
16,7e7d4d3ee5f05a38a6267888a8186ad2,2015-01-14,2015-01-23,1,1.0,1,0,0.0,0,0,...,16.3,32.4,80.0,88.2,170.0,Male,Chinese,Singaporean,1955-08-12,20754
17,823e89a2419de712c0e8fc3a42b9d0c4,2012-01-23,2012-01-29,0,1.0,0,0,0.0,0,0,...,12.4,26.2,82.0,59.5,165.0,f,Malay,Singaporean,1945-02-19,32742
18,87a483a68c73ae234498bc060f486908,2014-12-13,2014-12-27,1,0.0,0,1,0.0,0,0,...,12.9,27.9,102.0,66.7,159.0,Female,Chinese,Singaporean,1977-11-27,13579
19,a08ec4ff64c7c4ad2f87560e68acd5d5,2011-05-06,2011-05-23,0,1.0,0,0,0.0,0,0,...,12.3,28.1,79.0,66.3,161.0,Female,chinese,Singaporean,1947-11-08,24457
20,2e14e5fa058673fbdb4e525403be304a,2012-04-02,2012-04-09,1,1.0,No,0,0.0,1,0,...,14.4,27.8,90.0,89.2,177.0,m,Chinese,PR,1977-08-15,23512
21,e6b3aede1195f2cd8bc0ca27baf86255,2015-05-28,2015-06-09,0,0.0,0,0,0.0,1,1,...,17.3,23.3,113.0,61.0,172.0,Male,Malay,PR,1965-04-22,36892
22,31bf634e57e001b75034b598f3806d2c,2015-11-09,2015-11-23,0,0.0,0,0,0.0,0,0,...,12.2,25.6,80.0,70.6,172.0,m,chinese,Foreigner,1961-09-27,13370
23,b35f08230dbc37cb02e4c19c89261247,2014-01-09,2014-01-23,0,0.0,0,0,0.0,0,0,...,15.8,30.5,99.0,69.8,157.0,Female,Malay,Singaporean,1937-05-02,38777
24,53bce74ea43151196a040ff1de0500bf,2012-04-17,2012-04-26,0,0.0,0,0,0.0,0,0,...,12.7,28.6,111.0,95.3,165.0,Male,Chinese,Singapore citizen,1934-11-22,28294
25,dd8f81a50380e0f9238cda2728a5d842,2013-02-21,2013-03-03,0,0.0,0,0,0.0,0,1,...,13.1,27.6,65.0,83.4,167.0,Female,Malay,Singaporean,1971-06-18,31124
26,91db2ff2302e1bea6ac7afc6bab1a8c4,2015-10-20,2015-11-01,0,1.0,0,0,1.0,1,1,...,17.2,26.4,88.0,90.2,167.0,Male,Chinese,Singaporean,1973-04-23,14564
27,143f0e6182aea0b539ffc8a953d5ebdc,2015-04-20,2015-05-03,0,0.0,0,1,0.0,0,0,...,12.3,28.9,103.0,86.5,160.0,Female,Chinese,Singaporean,1946-02-05,22493
28,c18f4c4f3e9794cc1029dba46dda3461,2012-02-08,2012-02-17,0,0.0,0,0,NaN,0,1,...,15.9,28.5,78.0,70.1,171.0,Male,Chinese,Singaporean,1953-03-10,16228
29,a7b42601aa3cc6e39b6440c9b5de3be4,2013-07-02,2013-07-13,1,NaN,No,0,0.0,0,0,...,14.9,24.8,106.0,80.7,153.0,Female,Chinese,Singapore citizen,1965-01-11,28250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3370,329c307b4d4820bf0a3077abd86a4ad4,2014-03-13,2014-03-24,0,0.0,1,0,0.0,1,0,...,13.9,28.6,103.0,76.6,153.0,Female,Chinese,Singaporean,1970-01-03,11802
3371,930d4150c4a4a2c60e4b14edc0a835f9,2013-06-20,2013-06-30,0,1.0,0,0,0.0,0,0,...,13.8,31.1,120.0,78.6,173.0,Male,Chinese,Singaporean,1965-03-13,19116
3372,0a5da4e6b882ab14fc084a32ad5ede00,2014-11-07,2014-11-14,0,0.0,1,0,NaN,0,0,...,11.0,24.2,91.0,93.5,169.0,Male,chinese,Singapore citizen,1970-06-02,21325
3373,8c5ec7d890cc66bbf19a5ddce6ffeed8,2013-04-26,2013-05-08,0,1.0,0,0,1.0,0,1,...,13.8,22.6,77.0,97.1,174.0,Male,Chinese,Singaporean,1943-10-18,22773
3374,9df23439a82fb78447dcc4bea6835d0e,2012-02-04,2012-02-17,1,1.0,0,1,0.0,0,0,...,14.1,25.6,92.0,62.2,155.0,Female,Malay,Singapore citizen,1973-03-10,35289
3375,28aa9246d21de1b9f9f8cd1f742d5733,2015-03-12,2015-03-24,0,0.0,0,0,0.0,1,0,...,14.0,23.9,106.0,97.6,164.0,Male,Chinese,Singaporean,1976-05-04,17119
3376,430a8ba25f16e970a2409ebb25b10e45,2013-09-23,2013-10-02,0,0.0,0,0,0.0,0,0,...,14.1,31.1,121.0,82.9,161.0,Male,Malay,Singaporean,1968-07-27,27215
3377,2552386eb13d4d05b9452d06892363db,2015-11-23,2015-12-02,0,1.0,No,0,0.0,0,0,...,16.3,22.0,79.0,52.3,162.0,Female,Others,Singaporean,1948-12-14,14229
3378,762e1f278a976f6b355f821b784499b6,2014-01-14,2014-01-25,0,1.0,0,0,1.0,0,0,...,12.6,28.3,113.0,81.3,170.0,Male,Chinese,Singaporean,1973-09-10,10030
3379,a9f3900683c6c42a8471c7d592ba2efb,2013-09-27,2013-10-11,0,0.0,0,0,0.0,0,0,...,13.8,26.6,84.0,79.7,170.0,Male,Malay,Singapore citizen,1971-08-06,33275
3380,68c642c760c751964a6a42f952d76fe2,2015-09-10,2015-09-22,0,1.0,1,0,1.0,0,0,...,12.1,25.4,99.0,67.9,164.0,Female,Chinese,Singaporean,1970-05-18,12518
3381,dc0c4a4772e3fd65d0fe8f4b7b1c11dc,2013-04-14,2013-04-28,0,1.0,No,0,0.0,1,0,...,15.1,26.1,80.0,94.6,152.0,Female,Malay,Singaporean,1960-07-01,33406
3382,b90190a7fd6ad5ca0527115474c34c27,2011-05-17,2011-05-27,0,0.0,0,0,0.0,0,0,...,15.6,31.1,101.0,98.4,171.0,Male,Chinese,PR,1973-07-12,18120
3383,c8500f4abe05686dd56f530f9bd5cbbb,2013-03-06,2013-03-16,0,0.0,1,0,1.0,1,1,...,16.4,29.4,108.0,81.2,157.0,Female,Malay,Singaporean,1982-10-13,15433
3384,076c10fc3dd576405bd464219112735e,2011-12-05,2011-12-17,0,1.0,0,0,0.0,1,0,...,16.6,26.0,95.0,104.5,171.0,Male,Chinese,PR,1965-06-26,20344
3385,d1fd18b780729633312bee2c97831083,2013-02-01,2013-02-14,1,1.0,0,0,0.0,0,1,...,13.1,23.7,98.0,81.2,161.0,Male,Indian,Singaporean,1982-08-13,18148
3386,d55a7d52dc931f75a73984cbe0c9e568,2015-01-26,2015-02-11,0,0.0,1,0,0.0,1,1,...,13.9,26.6,88.0,88.1,162.0,Male,chinese,Singaporean,1957-01-06,25035
3387,3cbfe2e0ee62d07e9323b9cd5e7610ba,2014-04-20,2014-04-28,0,0.0,0,0,0.0,0,0,...,14.6,28.6,90.0,98.0,168.0,Male,Chinese,Singaporean,1972-10-20,17479
3388,bf4a1ab00a9de9fd508d67a59471b80c,2015-06-28,2015-07-13,0,NaN,0,0,NaN,1,1,...,14.3,27.0,86.0,86.7,161.0,Male,Chinese,Singaporean,1975-12-05,12729
3389,fe14b40134ff4e2fd574aac9805d29c8,2011-07-18,2011-07-26,0,0.0,No,0,0.0,1,0,...,14.4,24.6,118.0,93.4,174.0,Male,chinese,Singaporean,1973-10-17,18968
3390,5acbbf57d9297ecb9828ddf0b8d1e6da,2015-11-04,2015-11-12,0,1.0,0,0,NaN,0,0,...,18.5,28.4,108.0,82.9,165.0,Male,Malay,Singaporean,1956-01-17,26683
3391,96848594151ac33f3192a3483af09753,2015-05-13,2015-05-27,0,0.0,0,0,1.0,0,0,...,14.2,27.5,78.0,75.8,165.0,Male,Malay,Singapore citizen,1980-02-19,30577
3392,861a1eaa063568038c9b54af4980cde5,2013-09-27,2013-10-07,0,0.0,0,0,0.0,0,0,...,15.6,28.5,81.0,73.5,162.0,Female,Chinese,Singaporean,1948-02-28,19404
3393,52fdfa7f874fc92a5d1f73fd8a11911b,2012-08-17,2012-08-26,0,0.0,0,0,NaN,0,0,...,12.7,28.0,134.0,71.7,163.0,Female,Indian,Singapore citizen,1974-09-17,23655
3394,67d5260621d5602bed05ec588d9c3ccf,2015-01-07,2015-01-20,0,1.0,1,0,0.0,0,1,...,12.5,29.3,63.0,79.2,151.0,Female,chinese,Singapore citizen,1944-07-21,31240
3395,21d57214d564717bd9ee1a55b0f40555,2011-10-04,2011-10-13,0,0.0,0,0,0.0,0,0,...,15.1,24.1,89.0,89.0,170.0,Male,Others,Singaporean,1973-05-03,23922
3396,836498863454509ae1f0abc0dd128fa9,2013-06-03,2013-06-20,1,0.0,0,0,0.0,1,0,...,16.1,25.3,105.0,73.9,167.0,Female,Malay,Singaporean,1971-01-26,38530
3397,97e68baf7e61c438a501fc6df124d7b4,2015-07-27,2015-08-09,0,0.0,No,0,0.0,0,0,...,14.3,29.7,114.0,66.5,158.0,Female,Indian,Singaporean,1940-04-27,32764
3398,7373cb1310011241d432d36b25c5bca6,2011-09-17,2011-09-27,0,0.0,0,0,0.0,1,0,...,15.5,29.5,113.0,75.5,182.0,Male,Chinese,Singaporean,1973-09-14,22240
3399,c607942a9bebf9c61daf2c0da499ddf5,2013-09-16,2013-09-30,0,1.0,0,0,0.0,1,0,...,12.1,29.4,115.0,77.8,175.0,Male,Malay,Singaporean,1972-01-04,26263